kind: ReplicationController
apiVersion: v1
metadata:
  name: phoenix
  labels:
    run: phoenix
spec:
  replicas: 1
  selector:
    run: phoenix
  template:
    metadata:
      labels:
        run: phoenix
    spec:
      containers:
        - name: phoenix
          image: gcr.io/<%= project %>/tanx:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
      restartPolicy: Always
      dnsPolicy: ClusterFirst
